Add sun_tools tests
icy/pacapt pull request #194
Opened 2021-07-09 16:12 UTC by mondeja

- The test suite is slow (~26 min).
- I'm not running the `sun_tools` init function at build time because in the build process `grep` needs the option `-E` included in `ggrep` (GNU-grep) but at runtime only needs the default `grep` implementation in SunOS (see [helps of both binaries](https://github.com/mondeja/pacapt/runs/3022140738?check_suite_focus=true#step:3:3958)).

I'm thinking on split the tests between different workflow files using the [`push/pull_request.paths`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths) option of Github Actions to only execute those test suites affected for the proposed changes, but it would be in another PR. What do you think?

2021-07-09 17:57 UTC, icy commented
> > You can see the latest CI run [here](https://github.com/mondeja/pacapt/actions/runs/1015781139).
> 
>     * The test suite is slow (~25 min).

Do you have any  idea why it's slow? What is the major step ? (See below too)

> 
>     * I'm not running the `sun_tools` init function at build time because in the build process `grep` needs the option `-E` included in `ggrep` (GNU-grep), but at runtime only needs the default `grep` implementation in SunOS (see [helps of both binaries](https://github.com/mondeja/pacapt/runs/3022140738?check_suite_focus=true#step:3:3958)).

We don't really need to generate script/test file within SunOS. That can be great, but looked like installation of packages in SunOS was slow, we can try to avoid: It's possible to generate the `pacapt.dev` and `tests/tmp/sun_tools.sh` from the host OS (it's MacOS) before we start the `solaris-vm` action. All files will be synchronized later by the action.

What do you think?

> I'm thinking on split the tests between different workflow files using the [`push/pull_request.paths`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths) option of Github Actions to only execute those test suites affected for the proposed changes, but it would be in another PR. What do you think?

From a raw log (which will be expired in a couple of days): https://pipelines.actions.githubusercontent.com/AOcsjwzED7zRzFC330ClPpw3Ubtp1sbXXN4WGen2OTpM0d7gto/_apis/pipelines/1/runs/104/signedlogcontent/22?urlExpires=2021-07-09T17%3A51%3A05.3608215Z&urlSigningMethod=HMACV1&urlSignature=2xoqysn%2F%2FzAmM5RMgHaHJYN%2BFH9hYQgR%2FOY%2FV4lFFBs%3D

I can see that the stuff within sunos_vm takes kinda 10 minutes, and most of them is to install dependencies. I don't know  about the steps before that, but we can improve the dependency issue first.

2021-07-09 17:59 UTC, icy commented
I have to update my previous comment with new link . I wanted to provide a link to some raw logs but that's 1-time link and it's just expired.

2021-07-09 18:42 UTC, mondeja commented
> Do you have any idea why it's slow? What is the major step ? (See below too)

The SunOS virtual machine creation, takes around ~17 minutes.

> We don't really need to generate script/test file within SunOS. That can be great, but looked like installation of packages in SunOS was slow, we can try to avoid: It's possible to generate the pacapt.dev and tests/tmp/sun_tools.sh from the host OS (it's MacOS) before we start the solaris-vm action. All files will be synchronized later by the action.

Sure, this should increase the speed of the tests ~5 minutes :+1:

2021-07-09 19:00 UTC, icy commented
> > Do you have any idea why it's slow? What is the major step ? (See below too)
> 
> The SunOS virtual machine creation, takes around ~17 minutes.
> 
> > We don't really need to generate script/test file within SunOS. That can be great, but looked like installation of packages in SunOS was slow, we can try to avoid: It's possible to generate the pacapt.dev and tests/tmp/sun_tools.sh from the host OS (it's MacOS) before we start the solaris-vm action. All files will be synchronized later by the action.
> 
> Sure, this should increase the speed of the tests ~5 minutes +1

That's not much, but still good. I was reading the logs wrong (I thought that's 10 minutes). So going with push/pull_request.paths is  just fine. At my work, I define some simple format to invoke the tests upon request.and most of the time, developers will decide that well (path-based pattern doesn't work as the project is a huge mono-tree :D)

2021-07-09 19:53 UTC, icy commented
Down the rabbit hole:

* https://github.com/vmactions/solaris-vm/blob/13811b4cde4b621079aa7a7d545e0e06d1924cb6/index.js#L114
* * https://github.com/vmactions/solaris-builder/blob/0d83ac064c95e8eb87e2f11b6a5799f7348bdf61/index.js#L121
* * * https://github.com/vmactions/solaris-download/commit/24d41565da6eff1382bd1e2d7a5f48663b0946ec#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R3
* * * * https://www.oracle.com/solaris/solaris11/downloads/solaris11-vm-templates-downloads.html :This VM Template is for use in Oracle VM VirtualBox, a cross-platform tool that runs on Windows, Linux, Mac OS X, and Oracle Solaris. This template includes the desktop environment. 

This sounds too much to me =)) Basically we just need to start a base installation (with nothing much) where we can invoke ... `pacapt.dev` to install stuff. There is a huge space for improvements in the `solaris-vm` action project, but I'm not sure it's really worth.

2021-07-09 20:00 UTC, icy commented
I've created a ticket https://github.com/vmactions/solaris-vm/issues/11 let's see if there is any better way.

2021-07-10 09:36 UTC, mondeja commented
It seems that your prevision was better than mine, [now it takes ~16 min](https://github.com/mondeja/pacapt/runs/3033424923).

2021-07-11 19:16 UTC, icy requested changes

2021-07-11 19:16 UTC, icy commented on bin/compile.sh
> +  # implementation of grep in SunOS doesn't support the options `-E` and `-e`
I've had a minor fix to address this problem: https://github.com/icy/pacapt/pull/195 and I think you may not need this patch.

2021-07-11 19:16 UTC, icy commented on bin/compile.sh
> +  $GREP -Eqie '#!/usr/bin/env sh' -- "$@"
Should be fixed in https://github.com/icy/pacapt/pull/195/files

2021-07-11 19:51 UTC, icy commented on bin/compile.sh
> +  # implementation of grep in SunOS doesn't support the options `-E` and `-e`
but I think it's better to include that in your PR too. As I just don't have any sunOS machine here for test :dagger: Can you please do that? Many thanks

2021-07-12 09:37 UTC, icy approved these changes
Awesome, thanks a lot @mondeja ; and sorry for my belated response during the recent days.

2021-07-12 09:38 UTC, merged